# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-08 23:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cartera', '0001_initial'),
        ('Prestamos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recaudos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recaudo', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor del Abono')),
                ('id_cartera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cartera.Cartera', verbose_name='Almacen')),
                ('id_prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Prestamos.Prestamos', verbose_name='Abonar a Venta')),
            ],
        ),
    ]
