# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-07 01:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cartera', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateField(verbose_name='Fecha de Entrega')),
                ('valor_utilidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor de la Utilidad')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripci\xf3n')),
                ('id_cartera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cartera.Cartera', verbose_name='Almacen')),
            ],
        ),
    ]
